### ISSUE TITLE
Is there a way for getting logged-in user within the scheduled task?

### ISSUE THREAD

**Issue by vmusulainen** [VeliovGroup/josk#3] opened 2020-04-27 13:32 UTC
I launch the task within the onLogin handler. 
The task logic depends from logged in user.
Is there some way for getting logged-in user within the task?

I have tried do:

````Meteor.userId()````

and got error 

````Exception in callback of async function: Error: Meteor.userId can only be invoked in method calls or publications.````

Is there some way getting logged in user? 

If noway I see the following approach:  to set a flag for the user in the Users collection  before scheduling the task
````Meteor.users.update({_id: loggedInUser._id}, {$set: {updateMeInTask: true}})````

and drop this flag within the task? 

Or may be is possible to pass a text value to the task?

**Comment by dr-dimitru** [comment] 2020-05-03 17:52
Hello @vmusulainen ,

Scheduled tasks are stateless, and that means there's no way to get logged in user.
There is a way to get all logged in users at the given moment of the time when task runs.

Your suggested approach checking mongodb record is the correct way to work with data in scheduled tasks.

Feel free to close it in case if the issue is solved on your end.

**Closed** 2020-05-03 19:52 UTC
Labels: question

**Comment by dr-dimitru** [comment] 2020-05-03 21:10
@vmusulainen 

Please support this project with:
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Support [via patreon](https://patreon.com/dr_dimitru);
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).

**Comment by vmusulainen** [comment] 2020-05-03 21:57
Thank you for nice products and I already supported  your projects some days ago via PayPal.:)

**Comment by dr-dimitru** [comment] 2020-05-03 23:17
@vmusulainen thank you for your support.
Let me know if don't mind getting featured in our [supporters repo](https://github.com/VeliovGroup/supporters#supporters-1).
