### ISSUE TITLE
v3.1.0  causes a big issue with our legacy api 😭 esm

### ISSUE THREAD

**Issue by masterbater** [veliovgroup/josk#16] opened 2024-04-01 13:00 UTC
v3.1.0 causes a big issue with our deployment, josk is a peer dep of mail-time. You should use a major version if you suddenly change its module format.

Installing 3.0.2 fixes my issue

**Comment by dr-dimitru** [comment] 2024-04-01 22:12
@masterbater thank you for reporting on this one.

`v4.0.0` is coming up soon with major changes. While `v3.1.0` has no new features nor API changes. Only bump in `node` requirement to `>=14.20.0`, that explicitly indicated in `packages.json`. We ran extensive tests with every LTS, current, and maintenance branches of `node` everything went smooth as long as version was above `14.20.0`

Please share:
1. Node.js version
2. Exception, error, stack-trace
3. Any relevant logs

**Comment by dr-dimitru** [comment] 2024-04-02 19:34
@masterbater thank you for reporting this one. Please update to [`3.1.1`](https://github.com/veliovgroup/josk/releases/tag/3.1.1) and let me know if it works well

Feel free to close it in case if the issue is solved on your end.

**Closed** 2024-04-03 19:02 UTC
Labels: bug, enhancement
